name: S3 Artifacts Action
description: 'Upload artifacts to S3'
author: 'inorthisle'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  aws_access_key_id:
    description: 'AWS access key id'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_s3_bucket_name:
    description: 'AWS bucket name'
    required: true
  aws_region: 
    description: 'AWS region'
    required: true
  source_dir:
    required: true
    description: 'Directory to upload'
  destination_dir:
    required: false
    default: /
    description: 'Destination directory for upload'
outputs:
  object_key:
    description: 'object key'
  object_locations:
    description: 'object locations'
runs:
  using: 'node16'
  main: 'dist/index.js'
